### ISSUE TITLE
Sugestão de detalhamento do parágrafo 2

### ISSUE THREAD

**Issue by cellonovaes** [Arthur-Miertschink/BD1-CC1N-MorePower#5]
Sugiro explicar a diferença dos clientes Pessoa Fisica e Pessoa Juridia dentro da sua empresa.

Também seria interessante detalhar como é o papel de cada tipo de funcionário na sua empresa.

**Comment by joscarlossr** [comment]
README atualizado com a descrição da função de cada colaborador, além de falar do que o **cliente** precisa no sistema. 
Diferenciamos pessoas jurídicas perante as físicas e ajustamos as conjugações dos verbos para o presente.

Alterações feitas no commit 0d0963f com os componentes da equipe.
